# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
manuel = Person.create(:sex => "M", :name => "manuel")
mia = Person.create(:sex => "F", :name => "mia")
luis = Person.create(:sex => "M", :name => "luis")
rosa = Person.create(:sex => "F", :name => "rosa")
larry = Person.create(:sex => "M", :name => "larry")
louise = Person.create(:sex => "F", :name => "louise")
bob = Person.create(:sex => "M", :name => "bob")
ned = Person.create(:sex => "M", :name => "ned")
alison = Person.create(:sex => "F", :name => "alison")
maggie = Person.create(:sex => "F", :name => "maggie")
naomi = Person.create(:sex => "F", :name => "naomi")
marcel = Person.create(:sex => "M", :name => "marcel")
terry = Person.create(:sex => "F", :father_id => marcel.id, :name => "terry")
paul = Person.create(:sex => "M", :father_id => manuel.id, :mother_id => terry.id, :name => "paul")
emily = Person.create(:sex => "F", :father_id => luis.id, :mother_id => rosa.id, :name => "emily")
tommy = Person.create(:sex => "M", :father_id => larry.id, :mother_id => louise.id, :name => "tommy")
irene = Person.create(:sex => "F", :father_id => tommy.id, :mother_id => emily.id, :name => "irene")
jack = Person.create(:sex => "M", :father_id => bob.id, :mother_id => louise.id, :name => "jack")
paso = Person.create(:sex => "M", :father_id => jack.id, :mother_id => alison.id, :current_spouse_id => irene.id , :name => "paso")
titty = Person.create(:sex => "F", :father_id => paso.id, :mother_id => irene.id, :name => "titty")
rud = Person.create(:sex => "M", :father_id => paso.id, :mother_id => irene.id, :name => "rud")
mark = Person.create(:sex => "M", :father_id => paso.id, :mother_id => irene.id, :name => "mark", birth_date: "1984-01-22T18:22:59-05:00")
peter = Person.create(:sex => "M", :father_id => paul.id, :mother_id => titty.id, :name => "peter", birth_date: "1904-05-10T18:22:59-05:00", death_date: "1995-05-10T18:22:59-05:00")
sam = Person.create(:sex => "M", :father_id => mark.id, :mother_id => mia.id, :name => "sam")
charlie = Person.create(:sex => "M", :father_id => mark.id, :mother_id => mia.id, :name => "charlie")
john = Person.create(:sex => "M", :father_id => jack.id, :mother_id => alison.id, :name => "john")
barbara = Person.create(:sex => "F", :father_id => john.id, :mother_id => maggie.id, :name => "barbara")
mary = Person.create(:sex => "F", :father_id => paul.id, :mother_id => barbara.id, :name => "mary")
debby = Person.create(:sex => "F", :father_id => bob.id, :mother_id => louise.id, :name => "debby")
steve = Person.create(:sex => "M", :father_id => paul.id, :mother_id => titty.id, :name => "steve")
michelle = Person.create(:sex => "F", :father_id => ned.id, :mother_id => naomi.id, :name => "michelle")
beatrix = Person.create(:sex => "F", :father_id => paul.id, :mother_id => michelle.id, :name => "beatrix")
julian = Person.create(:sex => "M", :father_id => paul.id, :mother_id => michelle.id, :name => "julian")
ruben = Person.create(:sex => "M", :father_id => paul.id, :name => "ruben")